export const PERMISSIONS = {
  VIEW_ACCOUNT: 'VIEW_ACCOUNT',
  VIEW_SCHEDULE: 'VIEW_SCHEDULE',
  VIEW_PROJECT: 'VIEW_PROJECT',
  VIEW_USER: 'VIEW_USER',
  VIEW_TASK: 'VIEW_TASK',

  CREATE_SCHEDULE: 'CREATE_SCHEDULE',
  CREATE_TASK: 'CREATE_TASK',

  EDIT_TASK: 'EDIT_TASK',
  EDIT_PROJECT: 'EDIT_PROJECT',
};
