export const baseAPI = 'http://localhost:3000/api/v1';

export const API = {
  register: '/auth/register',
  login: '/auth/login',
  logout: '/auth/logout',
  getUser: '/auth/user',
  filterUser: '/auth/user/filter',
  updateUser: '/auth/user',
  getAllPermission: '/permission',
  addPermission: '/permission',
  getProject: '/project/{{projectId}}',
  filterProject: '/project/filter',
  updateProject: '/project/{{projectId}}',
  addProject: '/project',
  grantRole: '/auth/grantRole',
  getAllRole: '/role',
  addRole: '/role',
  updateRole: '/role',
  deleteRole: '/role/{{roleId}}',
  getAllSchedules: '/schedule',
  getSchedulesInRange: '/schedule/range',
  addSchedule: '/schedule',
  updateSchedule: '/schedule/{{scheduleId}}',
  addUserToSchedule: '/schedule/{{scheduleId}}',
  getTask: '/task/{{taskId}}',
  addTask: '/task/{{projectId}}',
  updateTask: '/task/{{taskId}}',
  updateAvatar: '/auth/avatar',
  deactiveUser: '/auth/user',
};
